In [7]:
import pandas as pd
import pandas_profiling as pp
import dtale
import seaborn as sns

import sys
sys.path.append(r"../../utils")

from utils import simple_eda
from sklearn.decomposition import PCA, KernelPCA, NMF
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
from umap import UMAP
from questions_columns import sci_af_ca,  scs_clin, sci_mother, sci_father, scs_stu
from sklearn.cluster import KMeans

In [3]:
df = pd.read_csv(r'../data_for_research.csv', na_values = ' ')
questions_text = False
activate_dtale = False
dim_reduction = UMAP

name = 'sci_af_ca'
df['sci_af_ca_sum'] = df[sci_af_ca].sum(axis=1)
df['sci_af_ca_missing_rate'] = df[sci_af_ca].isna().sum(axis=1) / len(sci_af_ca)

In [4]:
columns = sci_af_ca + ['sci_af_ca_sum', 'sci_af_ca_missing_rate']
# if questions_text:
#     simple_eda(df, columns = columns, title = name, path = '../pandas_profiling', rename = sci_af_ca_rename)
# else:
#     simple_eda(df, columns = columns, title = name, path = '../pandas_profiling',)

In [4]:
if activate_dtale:
    d = dtale.show(df[columns])
    d.open_browser()

In [10]:

sns.set(rc={'figure.figsize':(11,8)})
sns.set(font_scale=1.2)
plt.clf()
features = df[sci_af_ca]
features = features.dropna(how= 'any', axis=0)

# Instantiate PCA and fit_transform your features
model = dim_reduction(n_components=2)
model_features = model.fit_transform(features)


# Apply k-means clustering
kmeans = KMeans(n_clusters=2)
clusters = kmeans.fit_predict(model_features)


# Concatenate your PCA features with your target variable
model_df = pd.DataFrame(model_features, columns=['var1', 'var2'])

# Plot the output using Seaborn

#sns.scatterplot(x='var1', y='var2', data=model_df).figure.savefig(fr"../cluster_vis/{name}_vis.png") 
sns.scatterplot(x='var1', y='var2', hue=clusters, palette='viridis', data=model_df).figure.savefig(fr"../cluster_vis/{name}_vis.png") 


In [14]:
kmeans.cluster_centers_

array([[9.545334 , 2.0551114],
       [3.7029028, 4.7209053]], dtype=float32)

In [18]:
a =  model.inverse_transform([kmeans.cluster_centers_[0]])

In [19]:
b = model.inverse_transform([kmeans.cluster_centers_[1]])

In [27]:
import numpy as np

x = (a - b)[0]
np.where(x < -3)

(array([ 3,  8, 15, 16, 19, 22, 23], dtype=int64),)

In [28]:
x

array([ 0.11397421, -2.190793  , -1.3543977 , -3.0497158 , -1.571567  ,
       -2.4727035 , -2.1834068 , -2.0914583 , -3.179544  , -1.0730116 ,
       -0.9709539 , -2.1334546 , -2.377247  , -1.5442342 , -1.8698994 ,
       -3.1202912 , -3.1653361 , -2.5049882 , -2.6566129 , -3.722766  ,
       -2.8163319 , -2.3131044 , -3.170481  , -3.0580087 , -2.6395593 ,
       -1.2833974 , -2.34276   , -2.4657328 , -0.8190018 , -1.3515731 ,
       -1.6400794 , -2.1925862 , -2.6085129 , -1.4129307 , -2.8321981 ,
       -1.6478949 , -1.4341512 , -1.5716771 , -2.581475  , -1.6359522 ],
      dtype=float32)